In [24]:
# Import required libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [25]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [26]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [27]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first = True)

In [28]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [29]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [30]:
# Since the User_ID column doesn't give meaningful info, we drop the data in rows (axis = 1 means row)
dataset = dataset.drop("User ID", axis=1)
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [31]:
# Check the values counts. It will help to check the dataset balanced or not
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [32]:
X = dataset[["Age", "EstimatedSalary", "Gender_Male"]]
y = dataset["Purchased"]

In [33]:
X.shape

(400, 3)

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

In [35]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [36]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# getting ERROR when passing the 'penalties': ['12'], so I removed
params = {
                "kernel": ["linear", "rbf", "sigmoid"],
                "C": [10, 100, 1000, 2000],
                "gamma": ["auto", "scale"]
         }


grid = GridSearchCV(SVC(probability=True), params, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000], 'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [37]:
results = grid.cv_results_
print(results)

{'mean_fit_time': array([0.01417575, 0.0157464 , 0.01121206, 0.01190357, 0.01030598,
       0.00941906, 0.03902922, 0.01355424, 0.00819244, 0.04446702,
       0.01689186, 0.01008778, 0.32835197, 0.05212245, 0.0089015 ,
       0.3211854 , 0.04984398, 0.00974565, 0.6279459 , 0.07692885,
       0.00731511, 0.52541394, 0.06734943, 0.0088357 ]), 'std_fit_time': array([0.00074   , 0.00536241, 0.00189798, 0.00167435, 0.0009221 ,
       0.00127213, 0.00362458, 0.00247781, 0.00060058, 0.01417406,
       0.00538626, 0.00107985, 0.05537885, 0.00761874, 0.00172944,
       0.02701741, 0.01181626, 0.0023431 , 0.23328364, 0.02007679,
       0.00074438, 0.07363949, 0.01059656, 0.00173453]), 'mean_score_time': array([0.01014619, 0.00889668, 0.01291008, 0.00534592, 0.00713992,
       0.00611439, 0.00600438, 0.00746112, 0.00675435, 0.00708165,
       0.00616322, 0.00629683, 0.00512986, 0.00647702, 0.00600491,
       0.00408854, 0.006811  , 0.00751228, 0.00398221, 0.00407534,
       0.00456076, 0.00429621, 0.00559673, 0.00503368]), 'std_score_time': array([0.0040965 , 0.00183288, 0.00405274, 0.0006142 , 0.00104315,
       0.00059275, 0.00076647, 0.00202211, 0.00151159, 0.00171884,
       0.00094107, 0.0010819 , 0.00161473, 0.00136389, 0.0010794 ,
       0.00062468, 0.00097582, 0.00319013, 0.00046555, 0.00015838,
       0.00082304, 0.00069877, 0.00130098, 0.00107457]), 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 100, 100, 100, 100, 100, 100,
                   1000, 1000, 1000, 1000, 1000, 1000, 2000, 2000, 2000,
                   2000, 2000, 2000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_kernel': masked_array(data=['linear', 'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid',
                   'linear', 'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid',
                   'linear', 'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid',
                   'linear', 'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'sigmoid'}], 'split0_test_score': array([0.83598456, 0.89285714, 0.76905334, 0.83598456, 0.89285714,
       0.76905334, 0.83598456, 0.85531396, 0.76905334, 0.83598456,
       0.85531396, 0.76905334, 0.83598456, 0.83598456, 0.76905334,
       0.83598456, 0.83598456, 0.76905334, 0.83598456, 0.81914245,
       0.76905334, 0.83598456, 0.81914245, 0.76905334]), 'split1_test_score': array([0.78297094, 0.87564411, 0.73352309, 0.78297094, 0.87564411,
       0.73352309, 0.78297094, 0.89285714, 0.71428571, 0.78297094,
       0.89285714, 0.71428571, 0.78297094, 0.87564411, 0.71428571,
       0.78297094, 0.87564411, 0.71428571, 0.78297094, 0.85714286,
       0.71428571, 0.78297094, 0.8742536 , 0.71428571]), 'split2_test_score': array([0.6445993 , 0.84139824, 0.73054343, 0.6445993 , 0.84139824,
       0.61038961, 0.6445993 , 0.85943468, 0.75      , 0.6445993 ,
       0.85943468, 0.75      , 0.6445993 , 0.8585034 , 0.75      ,
       0.6445993 , 0.8585034 , 0.75      , 0.6445993 , 0.8585034 ,
       0.75      , 0.6445993 , 0.8585034 , 0.75      ]), 'split3_test_score': array([0.92777778, 0.94701493, 0.75387097, 0.92777778, 0.94701493,
       0.75387097, 0.92777778, 0.92914439, 0.68603604, 0.92777778,
       0.92914439, 0.75387097, 0.92777778, 0.91110549, 0.69486431,
       0.92777778, 0.91110549, 0.69486431, 0.92777778, 0.91110549,
       0.69486431, 0.92777778, 0.91110549, 0.69486431]), 'split4_test_score': array([0.8901138 , 0.94615252, 0.75990991, 0.8901138 , 0.94615252,
       0.75990991, 0.8901138 , 0.92857143, 0.75990991, 0.8901138 ,
       0.92857143, 0.75990991, 0.8901138 , 0.8901138 , 0.75990991,
       0.8901138 , 0.8901138 , 0.75990991, 0.8901138 , 0.92777778,
       0.75990991, 0.8901138 , 0.92777778, 0.75990991]), 'mean_test_score': array([0.81628928, 0.90061339, 0.74938015, 0.81628928, 0.90061339,
       0.72534938, 0.81628928, 0.89306432, 0.735857  , 0.81628928,
       0.89306432, 0.74942399, 0.81628928, 0.87427027, 0.73762266,
       0.81628928, 0.87427027, 0.73762266, 0.81628928, 0.8747344 ,
       0.73762266, 0.81628928, 0.87815654, 0.73762266]), 'std_test_score': array([0.09884858, 0.04102919, 0.01499564, 0.09884858, 0.04102919,
       0.05865238, 0.09884858, 0.03199566, 0.03107415, 0.09884858,
       0.03199566, 0.01870867, 0.09884858, 0.02578421, 0.02832207,
       0.09884858, 0.02578421, 0.02832207, 0.09884858, 0.0394964 ,
       0.02832207, 0.09884858, 0.03855397, 0.02832207]), 'rank_test_score': array([ 9,  1, 18,  9,  1, 24,  9,  3, 23,  9,  3, 17,  9,  7, 19,  9,  7,
       19,  9,  6, 19,  9,  5, 19], dtype=int32)}

In [38]:
grid_pred = grid.predict(X_test)
grid_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [39]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [40]:
matrix = confusion_matrix(y_test, grid_pred)

In [41]:
print(matrix)

[[73  6]
 [ 4 37]]

In [42]:
report = classification_report(y_test, grid_pred)
print(report)

              precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120

In [43]:
from sklearn.metrics import f1_score
f1_macro = f1_score(y_test, grid_pred, average="weighted")
print("The f1_macro value for best parameter {}:".format(grid.best_params_), f1_macro)

The f1_macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9171245421245421

In [44]:
from sklearn.metrics import roc_auc_score

# It will not work, if not provide the probability data (predict_proba)
roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])

0.9654214263661625

In [45]:
table = pd.DataFrame.from_dict(results)

In [46]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.014176,0.000740,0.010146,0.004096,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
1,0.015746,0.005362,0.008897,0.001833,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.892857,0.875644,0.841398,0.947015,0.946153,0.900613,0.041029,1
2,0.011212,0.001898,0.012910,0.004053,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.769053,0.733523,0.730543,0.753871,0.759910,0.749380,0.014996,18
3,0.011904,0.001674,0.005346,0.000614,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
4,0.010306,0.000922,0.007140,0.001043,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.892857,0.875644,0.841398,0.947015,0.946153,0.900613,0.041029,1
5,0.009419,0.001272,0.006114,0.000593,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.769053,0.733523,0.610390,0.753871,0.759910,0.725349,0.058652,24
6,0.039029,0.003625,0.006004,0.000766,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
7,0.013554,0.002478,0.007461,0.002022,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.855314,0.892857,0.859435,0.929144,0.928571,0.893064,0.031996,3
8,0.008192,0.000601,0.006754,0.001512,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.769053,0.714286,0.750000,0.686036,0.759910,0.735857,0.031074,23
9,0.044467,0.014174,0.007082,0.001719,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
10,0.016892,0.005386,0.006163,0.000941,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.855314,0.892857,0.859435,0.929144,0.928571,0.893064,0.031996,3
11,0.010088,0.001080,0.006297,0.001082,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.769053,0.714286,0.750000,0.753871,0.759910,0.749424,0.018709,17
12,0.328352,0.055379,0.005130,0.001615,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
13,0.052122,0.007619,0.006477,0.001364,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.835985,0.875644,0.858503,0.911105,0.890114,0.874270,0.025784,7
14,0.008902,0.001729,0.006005,0.001079,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.769053,0.714286,0.750000,0.694864,0.759910,0.737623,0.028322,19
15,0.321185,0.027017,0.004089,0.000625,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
16,0.049844,0.011816,0.006811,0.000976,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.835985,0.875644,0.858503,0.911105,0.890114,0.874270,0.025784,7
17,0.009746,0.002343,0.007512,0.003190,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.769053,0.714286,0.750000,0.694864,0.759910,0.737623,0.028322,19
18,0.627946,0.233284,0.003982,0.000466,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
19,0.076929,0.020077,0.004075,0.000158,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.819142,0.857143,0.858503,0.911105,0.927778,0.874734,0.039496,6
20,0.007315,0.000744,0.004561,0.000823,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.769053,0.714286,0.750000,0.694864,0.759910,0.737623,0.028322,19
21,0.525414,0.073639,0.004296,0.000699,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.835985,0.782971,0.644599,0.927778,0.890114,0.816289,0.098849,9
22,0.067349,0.010597,0.005597,0.001301,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.819142,0.874254,0.858503,0.911105,0.927778,0.878157,0.038554,5
23,0.008836,0.001735,0.005034,0.001075,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.769053,0.714286,0.750000,0.694864,0.759910,0.737623,0.028322,19

In [48]:
age = int(input("Age: "))
gender = int(input("Gender [Male=0, Female=1]: "))
est_salary = float(input("Est. Salary: "))

prediction = grid.predict([[age, gender, est_salary]])

prediction = "seems not purchase" if gender == 0 else "possible to purchase"
gender = "male" if gender == 0 else "female"

print("Using SVM: {} years old {} getting {} salary, is {}".format(age, gender, est_salary, prediction))

Age:  42
Gender [Male=0, Female=1]:  1
Est. Salary:  150000

Using SVM: 42 years old female getting 150000.0 salary, is possible to purchase