### Assignment: Chronic Kidney Disease Prediction
When doing in the VM, got memory out of error then I followed this in the base memory.

In [1]:
# Import required libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
# Check the values counts. It will help to check the dataset balanced or not
dataset["classification"].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [5]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [6]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first = True)

In [7]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [8]:
# Check the columns after encoding
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [9]:
X = dataset.drop(columns=['classification_yes'])
y = dataset["classification_yes"]

In [10]:
X

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [11]:
y

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [12]:
X.shape

(399, 27)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

In [14]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

In [15]:
X_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
92,41.0,80.0,1,4,210.0,165.0,18.0,135.0,4.7,12.518156,...,0,1,0,0,0,1,0,1,0,0
223,57.0,80.0,0,0,133.0,48.0,1.2,147.0,4.3,14.800000,...,1,1,0,0,0,0,0,1,0,0
234,59.0,100.0,4,2,255.0,132.0,12.8,135.0,5.7,7.300000,...,1,1,0,0,1,1,1,1,0,1
232,59.0,70.0,0,0,204.0,34.0,1.5,124.0,4.1,9.800000,...,1,1,0,0,0,1,0,1,0,0
336,70.0,80.0,0,0,158.0,85.0,3.2,141.0,3.5,10.100000,...,1,1,0,0,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68.0,70.0,0,0,98.0,86.0,4.6,135.0,3.4,9.800000,...,1,1,0,0,1,1,1,0,1,0
192,54.0,90.0,1,0,150.0,18.0,1.2,140.0,4.2,12.518156,...,1,0,0,0,0,0,0,0,1,1
117,45.0,80.0,0,0,107.0,15.0,1.0,141.0,4.2,11.800000,...,1,0,0,0,0,0,0,1,0,0
47,30.0,80.0,0,0,89.0,42.0,0.5,139.0,5.0,16.700000,...,1,1,0,0,0,0,0,1,0,0
172,51.0,60.0,0,0,129.0,25.0,1.2,139.0,5.0,17.200000,...,1,1,0,0,0,0,0,1,0,0

In [16]:
X_test

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
132,46.0,70.0,0,0,100.000000,47.0,0.5,142.000000,3.500000,16.400000,...,1,1,0,0,0,0,0,1,0,0
309,66.0,90.0,2,0,153.000000,76.0,3.3,137.528754,4.627244,12.518156,...,1,1,0,1,0,0,0,0,0,0
334,69.0,70.0,0,0,83.000000,42.0,1.2,139.000000,3.700000,16.200000,...,1,1,0,0,0,0,0,1,0,0
196,55.0,100.0,1,4,297.000000,53.0,2.8,139.000000,4.500000,11.200000,...,1,1,0,0,1,1,0,1,0,0
246,60.0,90.0,2,0,105.000000,53.0,2.3,136.000000,5.200000,11.100000,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,57.0,90.0,5,0,148.112676,322.0,13.0,126.000000,4.800000,8.000000,...,0,0,0,1,1,1,1,0,1,1
259,61.0,60.0,0,0,108.000000,75.0,1.9,141.000000,5.200000,9.900000,...,1,1,0,0,1,1,0,1,0,1
49,30.0,60.0,0,0,120.000000,31.0,0.8,150.000000,4.600000,13.400000,...,1,1,0,0,0,0,0,1,0,0
238,59.0,60.0,0,0,113.000000,23.0,1.1,139.000000,3.500000,15.300000,...,1,1,0,0,0,0,0,1,0,0
342,70.0,60.0,0,0,120.000000,40.0,0.5,140.000000,4.600000,16.000000,...,1,1,0,0,0,0,0,1,0,0

### RandomForestClassifer

In [71]:
# For flow testing
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(criterion="entropy", random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [73]:
rf_pred = classifier.predict(X_test)
rf_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [74]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

matrix = confusion_matrix(y_test, rf_pred)
matrix

array([[44,  1],
       [ 1, 74]])

In [75]:
report = classification_report(y_test, grid_pred)
print(report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

---

### LogisticRegression (With GV)

In [76]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# getting ERROR when passing the 'penalties': ['12'], so I removed
params = {
            'solver': ['newton-cg', 'lbfgs', 'saga']
         }

grid = GridSearchCV(LogisticRegression(), params, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")
grid.fit(X_train, y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'solver': ['newton-cg', 'lbfgs', 'saga']},
             scoring='f1_weighted', verbose=3)

In [77]:
results = grid.cv_results_
print(results)

{'mean_fit_time': array([0.1042582 , 0.03162379, 0.01954155]), 'std_fit_time': array([0.01600521, 0.00377243, 0.00101433]), 'mean_score_time': array([0.00790324, 0.00896955, 0.00880823]), 'std_score_time': array([0.00080912, 0.00156092, 0.00152179]), 'param_solver': masked_array(data=['newton-cg', 'lbfgs', 'saga'],
             mask=[False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'solver': 'newton-cg'}, {'solver': 'lbfgs'}, {'solver': 'saga'}], 'split0_test_score': array([1.        , 0.90911486, 0.48076923]), 'split1_test_score': array([0.96428571, 0.92777778, 0.48076923]), 'split2_test_score': array([0.96457219, 0.91110549, 0.48076923]), 'split3_test_score': array([0.94615252, 0.92914439, 0.48076923]), 'split4_test_score': array([1.        , 0.9817282 , 0.47231869]), 'mean_test_score': array([0.97500209, 0.93177414, 0.47907912]), 'std_test_score': array([0.02147423, 0.02630183, 0.00338022]), 'rank_test_score': array([1, 2, 3], dtype=int32)}

In [78]:
grid_pred = grid.predict(X_test)
grid_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [79]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [80]:
matrix = confusion_matrix(y_test, grid_pred)

In [81]:
print(matrix)

[[45  0]
 [ 0 75]]

In [82]:
report = classification_report(y_test, grid_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        75

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [83]:
from sklearn.metrics import f1_score
f1_macro = f1_score(y_test, grid_pred, average="weighted")
print("The f1_macro value for best parameter {}:".format(grid.best_params_), f1_macro)

The f1_macro value for best parameter {'solver': 'newton-cg'}: 1.0

In [49]:
# sample_input = [
#         63, 76.45994832041343, "c", 3, 0, "abnormal", "normal", "present", "notpresent", 
#         148.11267605633802, 57.482105263157905, 3.0773560209424087,	137.52875399361022,
#         4.62724359,	12.518155619596538,	38.86890243902439,	8408.191126279864,	4.705597014925374,
#         "yes", "yes", "no", "no", "yes", "no", "no"
# ]

---

### SVM Classifer (With CV)

In [17]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# getting ERROR when passing the 'penalties': ['12'], so I removed
params = {
                "kernel": ["linear", "rbf", "sigmoid"],
                "C": [10, 100, 1000],
                "gamma": ["auto", "scale"]
         }


grid = GridSearchCV(SVC(probability=True), params, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000], 'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [18]:
results = grid.cv_results_
print(results)

{'mean_fit_time': array([1.31533748e+02, 3.42000008e-02, 1.61760330e-02, 9.84788370e+01,
       2.22676754e-02, 1.55395031e-02, 1.27089345e+02, 3.06334972e-02,
       1.35390282e-02, 1.57141902e+02, 3.32992077e-02, 1.39105320e-02,
       1.72078884e+02, 3.60500336e-02, 1.65397644e-02, 1.61858775e+02,
       3.55435371e-02, 1.50136471e-02]), 'std_fit_time': array([6.47295285e+01, 1.45223529e-03, 2.25677312e-03, 5.02827982e+01,
       8.15965894e-04, 1.63520092e-03, 6.79209176e+01, 4.72964136e-04,
       4.97620126e-04, 7.19401198e+01, 6.16241346e-04, 1.82494323e-03,
       7.99379493e+01, 4.59902985e-04, 1.25757550e-03, 7.57654601e+01,
       3.16121535e-03, 1.58029555e-03]), 'mean_score_time': array([0.00644584, 0.01013718, 0.00781503, 0.00566945, 0.00679202,
       0.00589328, 0.00539522, 0.00658607, 0.00513024, 0.00519371,
       0.00896926, 0.0055604 , 0.00487437, 0.00800157, 0.00662079,
       0.00452952, 0.0066597 , 0.00622587]), 'std_score_time': array([4.86766745e-04, 1.18705040e-03, 1.06590555e-03, 1.71326178e-04,
       4.00007645e-04, 4.72241943e-04, 3.62609919e-04, 7.31695704e-05,
       2.12271408e-04, 2.32148110e-04, 1.10285239e-03, 2.30129339e-04,
       3.24602236e-04, 3.14491693e-04, 1.41533491e-03, 1.03212796e-03,
       2.03077853e-04, 2.74678625e-04]), 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 100, 100, 100, 100, 100, 100,
                   1000, 1000, 1000, 1000, 1000, 1000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=999999), 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_kernel': masked_array(data=['linear', 'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid',
                   'linear', 'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid',
                   'linear', 'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'}], 'split0_test_score': array([1.        , 0.48076923, 0.48076923, 1.        , 0.48076923,
       0.51537272, 1.        , 0.48076923, 0.48076923, 1.        ,
       0.7802276 , 0.51537272, 1.        , 0.48076923, 0.48076923,
       1.        , 0.87636816, 0.51537272]), 'split1_test_score': array([0.91110549, 0.48076923, 0.48076923, 0.91110549, 0.53125   ,
       0.5       , 0.92857143, 0.48076923, 0.48076923, 0.92857143,
       0.71111111, 0.5       , 0.92857143, 0.48076923, 0.48076923,
       0.92857143, 0.85902503, 0.51537272]), 'split2_test_score': array([0.94701493, 0.48076923, 0.48076923, 0.94701493, 0.48076923,
       0.57142857, 0.94701493, 0.48076923, 0.48076923, 0.94701493,
       0.62719298, 0.5394385 , 0.94701493, 0.48076923, 0.48076923,
       0.94701493, 0.82421875, 0.5394385 ]), 'split3_test_score': array([0.94615252, 0.48076923, 0.48076923, 0.94615252, 0.48076923,
       0.53055556, 0.94615252, 0.48076923, 0.48076923, 0.94615252,
       0.71753247, 0.53055556, 0.94615252, 0.48076923, 0.48076923,
       0.94615252, 0.84165303, 0.53055556]), 'split4_test_score': array([0.9817282 , 0.47231869, 0.47231869, 0.9817282 , 0.47231869,
       0.52121212, 0.96324675, 0.47231869, 0.47231869, 0.96324675,
       0.80636082, 0.52121212, 0.96324675, 0.47231869, 0.47231869,
       0.96324675, 0.90946957, 0.52121212]), 'mean_test_score': array([0.95720023, 0.47907912, 0.47907912, 0.95720023, 0.48917528,
       0.52771379, 0.95699713, 0.47907912, 0.47907912, 0.95699713,
       0.728485  , 0.52131578, 0.95699713, 0.47907912, 0.47907912,
       0.95699713, 0.86214691, 0.52439033]), 'std_test_score': array([0.03093205, 0.00338022, 0.00338022, 0.03093205, 0.02129043,
       0.02400702, 0.02413949, 0.00338022, 0.00338022, 0.02413949,
       0.06232788, 0.01344247, 0.02413949, 0.00338022, 0.00338022,
       0.02413949, 0.02935973, 0.00935086]), 'rank_test_score': array([ 1, 13, 13,  1, 12,  9,  3, 13, 13,  3,  8, 11,  3, 13, 13,  3,  7,
       10], dtype=int32)}

In [19]:
grid_pred = grid.predict(X_test)
grid_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0])

In [23]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

matrix = confusion_matrix(y_test, grid_pred)
matrix

array([[44,  1],
       [ 4, 71]])

In [24]:
report = classification_report(y_test, grid_pred)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        45
           1       0.99      0.95      0.97        75

    accuracy                           0.96       120
   macro avg       0.95      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120

----
### Decision Tree Classifier (CV)

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

params = {
        "criterion": ['gini', 'entropy', 'log_loss'],
        "splitter": ["best", "random"]
       }

grid = GridSearchCV(DecisionTreeClassifier(), params, refit=True, verbose=3, n_jobs=-1, scoring="f1_weighted")
grid.fit(X_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [26]:
results = grid.cv_results_
print(results)

{'mean_fit_time': array([0.01188507, 0.01041455, 0.01026711, 0.00642319, 0.00758338,
       0.0059195 ]), 'std_fit_time': array([0.00037217, 0.00171183, 0.00256375, 0.00273447, 0.00137866,
       0.00038087]), 'mean_score_time': array([0.00983734, 0.00846505, 0.00854368, 0.00719275, 0.00872188,
       0.00659781]), 'std_score_time': array([0.00051812, 0.00054605, 0.00229347, 0.00145694, 0.0008767 ,
       0.00067677]), 'param_criterion': masked_array(data=['gini', 'gini', 'entropy', 'entropy', 'log_loss',
                   'log_loss'],
             mask=[False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random'],
             mask=[False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'criterion': 'gini', 'splitter': 'best'}, {'criterion': 'gini', 'splitter': 'random'}, {'criterion': 'entropy', 'splitter': 'best'}, {'criterion': 'entropy', 'splitter': 'random'}, {'criterion': 'log_loss', 'splitter': 'best'}, {'criterion': 'log_loss', 'splitter': 'random'}], 'split0_test_score': array([0.96428571, 0.91169154, 1.        , 0.96457219, 1.        ,
       0.9822211 ]), 'split1_test_score': array([0.90911486, 0.96428571, 0.96388889, 0.9466633 , 0.94546891,
       0.96428571]), 'split2_test_score': array([0.89453125, 1.        , 0.87698413, 0.98205084, 0.87698413,
       0.92951252]), 'split3_test_score': array([0.92777778, 0.9466633 , 0.92777778, 0.96457219, 0.90911486,
       0.9822211 ]), 'split4_test_score': array([0.96363636, 1.        , 0.96363636, 0.98189391, 0.96363636,
       0.98189391]), 'mean_test_score': array([0.93186919, 0.96452811, 0.94645743, 0.96795049, 0.93904085,
       0.96802687]), 'std_test_score': array([0.02824396, 0.03354824, 0.04157222, 0.01318491, 0.04268227,
       0.02045776]), 'rank_test_score': array([6, 3, 4, 2, 5, 1], dtype=int32)}

In [27]:
grid_pred = grid.predict(X_test)
grid_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [28]:
matrix = confusion_matrix(y_test, grid_pred)
matrix

array([[45,  0],
       [ 3, 72]])

In [29]:
report = classification_report(y_test, grid_pred)
print(report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        45
           1       1.00      0.96      0.98        75

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120